Change flow

diff --git a/.github/workflows/full_build_pipeline_level_by_level.yml b/.github/workflows/full_build_pipeline_level_by_level.yml
--- a/.github/workflows/full_build_pipeline_level_by_level.yml
+++ b/.github/workflows/full_build_pipeline_level_by_level.yml
@@ -85,27 +85,27 @@ jobs:
           done
 
       - name: Checkout to Branch
-        run:
-          for module_name in $(jq -r '.standard_library| .[] | select(.level==${{ matrix.level }}) | .name' extensions.json); do
-          VERSION_KEY=$(jq -r ".standard_library | .[] | select(.name==\"$module_name\") | .version_key" extensions.json)
-          VERSION=$((grep -w $VERSION_KEY | cut -d= -f2) < gradle.properties)
-          version_split=($(echo $VERSION | tr "-" "\n"))
-          length=${#version_split[@]}
+        run: |
+          for module_name in $(jq -r '.standard_library| .[] | select(.level==${{ matrix.level }}) | .name' extensions.json); do \
+          VERSION_KEY=$(jq -r ".standard_library | .[] | select(.name==\"$module_name\") | .version_key" extensions.json) && \
+          VERSION=$((grep -w $VERSION_KEY | cut -d= -f2) < gradle.properties) && \
+          version_split=($(echo $VERSION | tr "-" "\n")) && \
+          length=${#version_split[@]} && \
 
-          if [ $(($length)) -gt 1 ];
-          then git checkout -b full-build ${version_split[@]:(-1)} || echo "Could not found commit ${version_split[@]:(-1)}";
-          elif [ "${{ steps.set-version.outputs.version }}" != "" ];
-          then git checkout v${{ steps.set-version.outputs.version }} || "Could not found branch v${{ steps.set-version.outputs.version }}";
-          else echo "${{ matrix.module }} is not packed with distribution.";
-          fi
+          if [ $(($length)) -gt 1 ]; \
+          then git checkout -b full-build ${version_split[@]:(-1)} || echo "Could not found commit ${version_split[@]:(-1)}"; \
+          elif [ "${{ steps.set-version.outputs.version }}" != "" ]; \
+          then git checkout v${{ steps.set-version.outputs.version }} || "Could not found branch v${{ steps.set-version.outputs.version }}"; \
+          else echo "${{ matrix.module }} is not packed with distribution."; \
+          fi && \
 
-          if [ "${{ matrix.module }}" == "module-ballerinai-transaction" ];
-          then git checkout 1.0.x || echo "Could not found branch 1.0.x";
-          fi
+          if [ "${{ matrix.module }}" == "module-ballerinai-transaction" ]; \
+          then git checkout 1.0.x || echo "Could not found branch 1.0.x"; \
+          fi && \
 
-          if [ "${{ matrix.module }}" == "module-ballerina-websubhub" ];
-          then git checkout 2201.0.x || echo "Could not found branch 2201.0.x";
-          fi
+          if [ "${{ matrix.module }}" == "module-ballerina-websubhub" ]; \
+          then git checkout 2201.0.x || echo "Could not found branch 2201.0.x"; \
+          fi && \
           done
 
 
